title: vacation_training_25
description: a simple site for the instruction of a training session.
theme: just-the-docs

url: https://jake0011.github.io/vacation_training_25

aux_links:
  my github: "https://jake0011.github.io/vacation_training_25"
  Dark Mode: #
